### ISSUE TITLE
setup.py has the wrong dependency

### ISSUE THREAD

**Issue by adamJLev** [roman-karpovich/drf-batch-requests#1]
Hi there,

Installing the package also triggers `django-rest-framework` to get installed, but the real package name is `djangorestframework`: https://pypi.python.org/pypi/djangorestframework.

Quick fix for sure - https://github.com/roman-karpovich/drf-batch-requests/blob/b8d9ca72be38c4cb5173e9d17b53da6f318193d0/setup.py#L25

Cheers 👍

**Comment by roman-karpovich** [comment]
@adamJLev thanks alot for your interest and suggestion :smile:
