### ISSUE TITLE
AttributeError: 'Response' object has no attribute '_headers'

### ISSUE THREAD

**Issue by himabinduyeddala** [roman-karpovich/drf-batch-requests#11]
I am trying to use drf_batch_requests==0.8.11 in django==3.2.13, when I was hitting the batch request it showed an error like AttributeError: 'Response' object has no attribute '_headers'. In lower versions of Django, it's working fine, but I need it in django3

If I am trying to update to the latest version it's not updated to 0.9.3. How can I resolve this issue? Please give me a reply about this ASAP.

Thanking You in Advance

**Comment by roman-karpovich** [comment]
Hi. Thanks for informing. I've released 0.9.5 version which should be compatible. Please let me know shall it resolve your issue or not.

**Comment by himabinduyeddala** [comment]
Hi Roman Karpovich,
Thank you for your immediate response and release of the latest version. I have updated the version with 0.9.5 for django==3.2.13, Now the issue was resolved. It's very helpful for me.

Thank You
Hima Bindu Y

**Comment by roman-karpovich** [comment]
Cool! Thanks again for pointing to the issue.
