### ISSUE TITLE
There's an error in views.py

### ISSUE THREAD

**Issue by tonipiano** [roman-karpovich/drf-batch-requests#4]
Hi there,

I've got an exception when I tried to use /batch endpoint for post requests: `ValueError: No JSON object could be decoded`.

The problem was in the 72nd line of views.py. The original code snippet:
```
if is_success(response.status_code):
    result['_data'] = json.loads(result['body'])
```
I've resolve the problem with following code snippet:
```
if is_success(response.status_code):
    result['_data'] = result['body']
```

So it's unnecessary to deserialize `result['body']`.

Have a nice day :)

**Comment by roman-karpovich** [comment]
thanks a lot for your feedback, it's very helpfull! i'll update the code
according to suggestion.

пн, 27 авг. 2018 г., 18:56 Tamás Csatlós <notifications@github.com>:

**Comment by roman-karpovich** [comment]
https://github.com/roman-karpovich/drf-batch-requests/commit/241075936ca81f6abdec12a8ea3dc9c9d0511cb6
