### ISSUE TITLE
Request 'name' in response

### ISSUE THREAD

**Issue by dacotagh** [roman-karpovich/drf-batch-requests#7]
Hi!

Is it possible to include name from request to response (to identify multiple get requests)?

It seems that something like

`                    'name': current_request.name,`

in **drf_batch_requests/views.py** added to

`                result = {`

is enough.

**Comment by roman-karpovich** [comment]
done. also i dropped support for outdated django versions. please let me know if that's problem for you.

**Comment by dacotagh** [comment]
Thank you for quick response.

Yes, it is the problem, we're still using django 1.11 (

At least do these changes in different versions )

**Comment by roman-karpovich** [comment]
python2.7, i guess?

**Comment by dacotagh** [comment]
No, 3.6 )

**Comment by roman-karpovich** [comment]
ok, returned back django 1.11 to tox :) uploaded 0.9.2 release

**Comment by dacotagh** [comment]
Thank you!

Still can't see 0.9.2 version in pip - does it delays or what?

**Comment by roman-karpovich** [comment]
my bad. seems i messed pypi versions a bit while trying to update requirements in setup file. uploaded 0.9.3 :(

**Comment by dacotagh** [comment]
Great!
