### ISSUE TITLE
More response error fields

### ISSUE THREAD

**Issue by dacotagh** [roman-karpovich/drf-batch-requests#9]
Another question:

drf has several fields in response in case of error:
- status (currently returned as code),
- statusText (not returned),
- body (returned),
- body.detail in some cases (not returned),

Is it possible to mimic DRF error responses?..

**Comment by roman-karpovich** [comment]
you're right, it's a good idea to refine returned fields. i'll try to check them in a few days

**Comment by roman-karpovich** [comment]
@dacotagh hello! can you please clarify what did you mean by body.detail? i'm unable to find suitable scenario where we'll need to have body AND some body attributes

**Comment by dacotagh** [comment]
For example, if user is not logged in (or logged out in other tab), drf will response with error.body {"detail":"Authentication credentials were not provided."}

**Comment by roman-karpovich** [comment]
in such case you can just get if from body for example json.loads(response.body)['detail']

**Comment by dacotagh** [comment]
Yes, but it leads to different approaches with and without batch )

**Comment by roman-karpovich** [comment]
but... even in standard case you parse (not with hands, but anyway) response body to get dict with required information. the only difference is the source field to be parsed as json. i just thinking about more handy solution, because duplicated body can lead to huge responses

**Comment by dacotagh** [comment]
It is not response body, but error body.
And it is not the case when Error 500 with huge debug page is in the response.

But anyway - I was sure that there is drf response/error with all fields and task is to place them to batch response, no?

**Comment by roman-karpovich** [comment]
according to http specification response consists of location headers and body. there is no specific place for error details. so, drf have no other choice than place info to the body coded as json
for example '{"errors": [...], "detail": "Something went wrong"}'

yep. and at this moment i added status text to response, because i also heared from our front-end developers that they sometimes use such info. i just don't want to duplicate data if it already exists in response

**Comment by dacotagh** [comment]
BTW, we've moved to django 2.2, so you can drop support of 1.11 if you want )

**Comment by roman-karpovich** [comment]
good news

**Comment by roman-karpovich** [comment]
is the original issue is still actual?

**Comment by dacotagh** [comment]
Yeah, it'll be great.

**Comment by roman-karpovich** [comment]
okay. so, let's clarify the problem again:

> status (currently returned as code),
> statusText (not returned),
> body (returned),
> body.detail in some cases (not returned),

at this moment there are status with text and a body (if not omitted by flag). body.detail is just a data field which is not http generic or so. it's just an optional which can be included in response json. or even can not be used at all, if we talk for example about plain http responses.

so, as for me, there is full set of possible data in response. please correct me if i'm missing something
